In [106]:
import sys
print(sys.executable)

d:\Vanshika_reja\venv\python.exe

In [107]:
import pandas as pd
import matplotlib.pyplot as plt
print(pd.__version__)

2.3.3

In [108]:
trade_history = pd.read_csv(r"D:\Vanshika_reja\Need\CSV_files\historical_data.csv")
df1 = trade_history.copy()
df1.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12

In [109]:
df1.shape

(211224, 16)

In [110]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  object
 1   Coin              211224 non-null  object
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  object
 6   Timestamp IST     211224 non-null  object
 7   Start Position    211224 non-null  float64
 8   Direction         211224 non-null  object
 9   Closed PnL        211224 non-null  float64
 10  Transaction Hash  211224 non-null  object
 11  Order ID          211224 non-null  int64
 12  Crossed           211224 non-null  bool
 13  Fee               211224 non-null  float64
 14  Trade ID          211224 non-null  float64
 15  Timestamp         211224 non-null  float64
dtypes: bool(1), float64(8), int64(1), object(6)
memory usage: 24.4+ MB

In [111]:
df1.describe()

,Execution Price,Size Tokens,Size USD,Start Position,Closed PnL,Order ID,Fee,Trade ID,Timestamp
count,211224.000000,2.112240e+05,2.112240e+05,2.112240e+05,211224.000000,2.112240e+05,211224.000000,2.112240e+05,2.112240e+05
mean,11414.723350,4.623365e+03,5.639451e+03,-2.994625e+04,48.749001,6.965388e+10,1.163967,5.628549e+14,1.737744e+12
std,29447.654868,1.042729e+05,3.657514e+04,6.738074e+05,919.164828,1.835753e+10,6.758854,3.257565e+14,8.689920e+09
min,0.000005,8.740000e-07,0.000000e+00,-1.433463e+07,-117990.104100,1.732711e+08,-1.175712,0.000000e+00,1.680000e+12
25%,4.854700,2.940000e+00,1.937900e+02,-3.762311e+02,0.000000,5.983853e+10,0.016121,2.810000e+14,1.740000e+12
50%,18.280000,3.200000e+01,5.970450e+02,8.472793e+01,0.000000,7.442939e+10,0.089578,5.620000e+14,1.740000e+12
75%,101.580000,1.879025e+02,2.058960e+03,9.337278e+03,5.792797,8.335543e+10,0.393811,8.460000e+14,1.740000e+12
max,109004.000000,1.582244e+07,3.921431e+06,3.050948e+07,135329.090100,9.014923e+10,837.471593,1.130000e+15,1.750000e+12

In [112]:
df1.isnull().sum()

Account             0
Coin                0
Execution Price     0
Size Tokens         0
Size USD            0
Side                0
Timestamp IST       0
Start Position      0
Direction           0
Closed PnL          0
Transaction Hash    0
Order ID            0
Crossed             0
Fee                 0
Trade ID            0
Timestamp           0
dtype: int64

In [113]:
df1["Account"].unique()

array(['0xae5eacaf9c6b9111fd53034a602c192a04e082ed',
       '0x72c6a4624e1dffa724e6d00d64ceae698af892a0',
       '0x513b8629fe877bb581bf244e326a047b249c4ff1',
       '0x083384f897ee0f19899168e3b1bec365f52a9012',
       '0x430f09841d65beb3f27765503d0f850b8bce7713',
       '0x8381e6d82f1affd39a336e143e081ef7620a3b7f',
       '0x4f93fead39b70a1824f981a54d4e55b278e9f760',
       '0x75f7eeb85dc639d5e99c78f95393aa9a5f1170d4',
       '0x420ab45e0bd8863569a5efbb9c05d91f40624641',
       '0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23',
       '0x23e7a7f8d14b550961925fbfdaa92f5d195ba5bd',
       '0x6d6a4b953f202f8df5bed40692e7fd865318264a',
       '0xbaaaf6571ab7d571043ff1e313a9609a10637864',
       '0xaf40fdc468c30116bd3307bcbf4a451a7ebf1deb',
       '0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891',
       '0xa0feb3725a9335f49874d7cd8eaad6be45b27416',
       '0x8477e447846c758f5a675856001ea72298fd9cb5',
       '0x8170715b3b381dffb7062c0298972d4727a0a63b',
       '0x47add9a56df66b524d5e2c1993a43cde53b6ed85',
       '0x3f9a0aadc7f04a7c9d75dc1b5a6ddd6e36486cf6',
       '0x28736f43f1e871e6aa8b1148d38d4994275d72c4',
       '0x39cef799f8b69da1995852eea189df24eb5cae3c',
       '0x7f4f299f74eec87806a830e3caa9afa5f2b9db8f',
       '0xa520ded057a32086c40e7dd6ed4eb8efb82c00e0',
       '0xb899e522b5715391ae1d4f137653e7906c5e2115',
       '0x2c229d22b100a7beb69122eed721cee9b24011dd',
       '0xbee1707d6b44d4d52bfe19e41f8a828645437aab',
       '0x4acb90e786d897ecffb614dc822eb231b4ffb9f4',
       '0x92f17e8d81a944691c10e753af1b1baae1a2cd0d',
       '0xbd5fead7180a9c139fa51a103cb6a2ce86ddb5c3',
       '0x271b280974205ca63b716753467d5a371de622ab',
       '0x72743ae2822edd658c0c50608fd7c5c501b2afbd'], dtype=object)

In [114]:
df1["timestamp_ist"] = pd.to_datetime(df1["Timestamp IST"], format="%d-%m-%Y %H:%M")

In [115]:
df1["trade_date"] = df1["timestamp_ist"].dt.date
df1["trade_time"] = df1["timestamp_ist"].dt.time

In [116]:
df1.head(1)

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp,timestamp_ist,trade_date,trade_time
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.0,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12,2024-12-02 22:50:00,2024-12-02,22:50:00

In [117]:
df1.drop(df1[["timestamp_ist", "Timestamp IST"]], axis=1, inplace=True)

In [118]:
df1.head(1)

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp,trade_date,trade_time
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,0.0,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12,2024-12-02,22:50:00

In [119]:
df1["Coin"].unique()

array(['@107', 'AAVE', 'DYDX', 'AIXBT', 'GMX', 'EIGEN', 'HYPE', 'SOL',
       'SUI', 'DOGE', 'ETH', 'kPEPE', 'TRUMP', 'ONDO', 'ENA', 'LINK',
       'XRP', 'S', 'BNB', 'BERA', 'WIF', 'LAYER', 'MKR', 'KAITO', 'IP',
       'JUP', 'USUAL', 'ADA', 'BTC', 'PURR/USDC', 'ZRO', '@7', '@19',
       '@21', '@44', '@48', '@11', '@15', '@46', '@61', '@28', '@45',
       '@9', '@41', '@38', 'kSHIB', 'GRASS', 'TAO', 'AVAX', '@2', '@6',
       '@8', '@10', '@12', '@16', '@17', '@35', '@26', '@24', '@32',
       '@29', '@31', '@33', '@34', '@36', '@37', '@47', '@53', '@74',
       'RUNE', 'CANTO', 'NTRN', 'BLUR', 'ZETA', 'MINA', 'MANTA', 'RNDR',
       'WLD', 'kBONK', 'ALT', 'INJ', 'STG', 'ZEN', 'MAVIA', 'PIXEL',
       'ILV', 'FET', 'STRK', 'CAKE', 'STX', 'ACE', 'PENDLE', 'AR', 'XAI',
       'APE', 'MEME', 'NEAR', 'SEI', 'FTM', 'MYRO', 'BIGTIME', 'IMX',
       'BADGER', 'POLYX', 'OP', 'TNSR', 'MAV', 'TIA', 'MERL', 'TON',
       'PURR', 'ME', 'CRV', 'BRETT', 'CHILLGUY', 'MOODENG', 'VIRTUAL',
       'COMP', 'FARTCOIN', 'AI16Z', 'GRIFFAIN', 'ZEREBRO', 'SPX',
       'MELANIA', 'PENGU', 'JELLY', 'VVV', 'VINE', 'TST', 'ARK', 'YGG',
       'POPCAT', 'NIL', 'MOVE', 'BABY', 'RENDER', 'PROMPT', 'WCT', 'OGN',
       'HYPER', 'ZORA', 'BIO', 'INIT', 'TURBO', 'ARB', '@142', 'JTO',
       'PYTH', 'MATIC', 'HPOS', 'FXS', 'FIL', 'SHIA', 'PEOPLE', 'UNI',
       'SUSHI', 'LOOM', 'USTC', 'RLB', 'ETC', 'GAS', 'BANANA', 'UNIBOT',
       'CYBER', 'GMT', 'ENS', 'DYM', 'ETHFI', '@4', '@3', '@20', '@14',
       '@51', '@125', '@109', '@85', '@59', '@23', '@78', 'GOAT', 'LDO',
       'PNUT', '@138', '@151', '@18', '@25', '@42', '@13', '@40', '@39',
       '@30', '@103', '@100', '@135', '@116', '@147', '@152', '@153',
       'ANIME', 'W', 'ORDI', 'IO', 'GALA', 'AI', 'NEIROETH', 'SAND',
       'BOME', 'MEW', 'SUPER', 'ALGO', 'HBAR', 'APT', 'BLAST', 'kNEIRO',
       'ATOM', 'DOT', 'kFLOKI', 'TRX', 'FTT', '@1', '@83', '@124', '@112',
       '@95', 'LISTA', 'LTC', 'RSR', 'MNT', '@113', 'ZK', '@117', '@86',
       '@68', '@63', 'MORPHO', 'OM', 'REZ', 'REQ', '@49', 'BNT', 'SCR',
       'IOTA', '@93', '@114', '@123', 'PAXG'], dtype=object)

In [120]:
is_win_list =[]
for i in df1["Closed PnL"]:
  if i>0:
    is_win_list.append(1)
  else:
    is_win_list.append(0)
df1["is_win"]=is_win_list

In [121]:
df1.head(1)

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp,trade_date,trade_time,is_win
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,0.0,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12,2024-12-02,22:50:00,0

In [122]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  object
 1   Coin              211224 non-null  object
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  object
 6   Start Position    211224 non-null  float64
 7   Direction         211224 non-null  object
 8   Closed PnL        211224 non-null  float64
 9   Transaction Hash  211224 non-null  object
 10  Order ID          211224 non-null  int64
 11  Crossed           211224 non-null  bool
 12  Fee               211224 non-null  float64
 13  Trade ID          211224 non-null  float64
 14  Timestamp         211224 non-null  float64
 15  trade_date        211224 non-null  object
 16  trade_time        211224 non-null  object
 17  is_win            211224 non-null  int64
dtypes: bool(1), float64(8), int64(2), object(7)
memory usage: 27.6+ MB

In [123]:
df1["trade_date"] = pd.to_datetime(df1["trade_date"])

In [124]:
df1[["trade_date", "trade_time"]].dtypes

trade_date    datetime64[ns]
trade_time            object
dtype: object

In [125]:
df1.drop(columns=["Order ID", "Trade ID", "Crossed"], axis=1, inplace=True)

In [126]:
df1.head(1)

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Start Position,Direction,Closed PnL,Transaction Hash,Fee,Timestamp,trade_date,trade_time,is_win
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,0.0,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,0.345404,1.730000e+12,2024-12-02,22:50:00,0

In [127]:
df1["Transaction Hash"].unique()

array(['0xec09451986a1874e3a980418412fcd0201f500c95bac0f37caef8a734502ec49',
       '0x21b8b230ad8a3e9ae1bb041841332f02028300681b0dd484959026f37947df17',
       '0xef8b5ed662586d4455030418413ecd01f3009832c599baba9307c5e77a0a81f3',
       ...,
       '0x0780085b0c0a943eea800422374d920204c100edf57920b301001a1ef729e674',
       '0x349c29934913b25c89e20422374d920204cd008b8a0e4170e03ec463010af3c4',
       '0xac77fab973c455d77a670422374d9602039800f1f78c7c3123205e2b7af37374'],
      shape=(101184,), dtype=object)

In [128]:
df1

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Start Position,Direction,Closed PnL,Transaction Hash,Fee,Timestamp,trade_date,trade_time,is_win
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,0.000000,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,0.345404,1.730000e+12,2024-12-02,22:50:00,0
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,986.524596,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,0.005600,1.730000e+12,2024-12-02,22:50:00,0
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,1002.518996,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,0.050431,1.730000e+12,2024-12-02,22:50:00,0
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,1146.558564,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,0.050043,1.730000e+12,2024-12-02,22:50:00,0
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,1289.488521,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,0.003055,1.730000e+12,2024-12-02,22:50:00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211219,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,382.20,420.80,SELL,7546.600000,Close Long,-20.2566,0xcd339c08dc7b615a993c0422374d8e02027400092bc2...,0.042080,1.750000e+12,2025-04-25,15:35:00,0
211220,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,2124.10,2338.63,SELL,7164.400000,Close Long,-112.5773,0x29e8ede2a3a37aa0eac00422374d8e02029b00ac9f3c...,0.233863,1.750000e+12,2025-04-25,15:35:00,0
211221,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,423.40,466.16,SELL,5040.300000,Close Long,-22.4402,0x0780085b0c0a943eea800422374d920204c100edf579...,0.046616,1.750000e+12,2025-04-25,15:35:00,0
211222,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,3599.80,3963.38,SELL,4616.900000,Close Long,-190.7894,0x349c29934913b25c89e20422374d920204cd008b8a0e...,0.396337,1.750000e+12,2025-04-25,15:35:00,0
211223,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,1017.10,1119.83,SELL,1017.100000,Close Long,-53.9063,0xac77fab973c455d77a670422374d9602039800f1f78c...,0.111982,1.750000e+12,2025-04-25,15:35:00,0

In [129]:
hash_counts = df1["Transaction Hash"].value_counts()
repeated_hashes = hash_counts[hash_counts > 1].index
repeated_hashes[:5]

Index(['0x0000000000000000000000000000000000000000000000000000000000000000',
       '0x8543ffeb4fdab50bfa0304222f29b702012700b5ee6b85c21ed9215e3bc8ba45',
       '0xb3a9e6e4f5293d501bb3041f5c49ec02018b00ecdfb8798414bcd103222f2c30',
       '0xa67acabfc24d0cb5d05b041f1704590204f000525423d8cded7ec70825f7b658',
       '0x6b313e029807198fba0f04215de94801ac001092edd85e7c214059795735b0c6'],
      dtype='object', name='Transaction Hash')

In [130]:
sample_hash=repeated_hashes[0]
sample_rows=df1[df1["Transaction Hash"]== sample_hash]
print(sample_rows[[
    "Account", "Coin", "Timestamp", 
    "Size USD", "Closed PnL", "Fee"]])

                                           Account      Coin     Timestamp  \
189     0xae5eacaf9c6b9111fd53034a602c192a04e082ed      @107  1.730000e+12
583     0x72c6a4624e1dffa724e6d00d64ceae698af892a0     EIGEN  1.730000e+12
584     0x72c6a4624e1dffa724e6d00d64ceae698af892a0     EIGEN  1.730000e+12
585     0x72c6a4624e1dffa724e6d00d64ceae698af892a0     EIGEN  1.730000e+12
586     0x72c6a4624e1dffa724e6d00d64ceae698af892a0     EIGEN  1.730000e+12
...                                            ...       ...           ...
210740  0x72743ae2822edd658c0c50608fd7c5c501b2afbd      @107  1.740000e+12
210742  0x72743ae2822edd658c0c50608fd7c5c501b2afbd      @107  1.740000e+12
210743  0x72743ae2822edd658c0c50608fd7c5c501b2afbd      @107  1.740000e+12
210744  0x72743ae2822edd658c0c50608fd7c5c501b2afbd      @107  1.740000e+12
211048  0x72743ae2822edd658c0c50608fd7c5c501b2afbd  FARTCOIN  1.750000e+12

        Size USD  Closed PnL       Fee
189         0.10    0.000000  0.000000
583        54.73    0.000000  0.005253
584        70.75    0.000000  0.006792
585        58.72    0.000000  0.005637
586        73.44    0.000000  0.007050
...          ...         ...       ...
210740     11.51    0.103854  0.001151
210742     11.51    0.103854  0.001151
210743     24.74    0.223208  0.002473
210744     35.91    0.323961  0.003590
211048     13.85    0.000000  0.001384

[9032 rows x 6 columns]

In [131]:
df1.drop(columns=["Transaction Hash"], axis=1, inplace=True)

In [132]:
df1.head(2)

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Start Position,Direction,Closed PnL,Fee,Timestamp,trade_date,trade_time,is_win
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,0.000000,Buy,0.0,0.345404,1.730000e+12,2024-12-02,22:50:00,0
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,986.524596,Buy,0.0,0.005600,1.730000e+12,2024-12-02,22:50:00,0

In [133]:
daily_df= (
  df1.groupby(["Account", "trade_date"]).agg(
    total_daily_pnl= ("Closed PnL", "sum"),
    num_trades = ("Closed PnL", "count"),
    wins= ("is_win", "sum"),
    avg_size_used = ("Size USD", "mean"),
    avg_fee= ("Fee", "mean")
  ).reset_index()
)

daily_df["win_rate"]= daily_df["wins"] /daily_df["num_trades"]

In [134]:
df1["Account"].nunique()

32

In [135]:
daily_df

,Account,trade_date,total_daily_pnl,num_trades,wins,avg_size_used,avg_fee,win_rate
0,0x083384f897ee0f19899168e3b1bec365f52a9012,2024-11-11,0.000000,177,0,5089.718249,0.948000,0.000000
1,0x083384f897ee0f19899168e3b1bec365f52a9012,2024-11-17,0.000000,68,0,7976.664412,0.998288,0.000000
2,0x083384f897ee0f19899168e3b1bec365f52a9012,2024-11-18,0.000000,40,0,23734.500000,2.373450,0.000000
3,0x083384f897ee0f19899168e3b1bec365f52a9012,2024-11-22,-21227.000000,12,0,28186.666667,2.818666,0.000000
4,0x083384f897ee0f19899168e3b1bec365f52a9012,2024-11-26,1603.100000,27,12,17248.148148,3.874907,0.444444
...,...,...,...,...,...,...,...,...
2336,0xbee1707d6b44d4d52bfe19e41f8a828645437aab,2025-04-27,1709.194807,82,32,2153.859390,0.312681,0.390244
2337,0xbee1707d6b44d4d52bfe19e41f8a828645437aab,2025-04-28,4008.588908,430,169,1495.538419,0.371047,0.393023
2338,0xbee1707d6b44d4d52bfe19e41f8a828645437aab,2025-04-29,8561.771838,902,398,1939.739989,0.386831,0.441242
2339,0xbee1707d6b44d4d52bfe19e41f8a828645437aab,2025-04-30,2520.773814,75,39,1748.805333,0.270870,0.520000
2340,0xbee1707d6b44d4d52bfe19e41f8a828645437aab,2025-05-01,1364.022527,131,43,2448.466489,0.457253,0.328244

In [136]:
sentiment_df = pd.read_csv(r"D:\Vanshika_reja\Need\CSV_files\fear_greed_index.csv")
df2 = sentiment_df.copy()
df2.head()

    timestamp  value classification        date
0  1517463000     30           Fear  2018-02-01
1  1517549400     15   Extreme Fear  2018-02-02
2  1517635800     40           Fear  2018-02-03
3  1517722200     24   Extreme Fear  2018-02-04
4  1517808600     11   Extreme Fear  2018-02-05

In [137]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       2644 non-null   int64
 1   value           2644 non-null   int64
 2   classification  2644 non-null   object
 3   date            2644 non-null   object
dtypes: int64(2), object(2)
memory usage: 82.8+ KB

In [138]:
df2 = df2.rename(columns={
  "date": "trade_date",
  "classification": "sentiment_class"
})

In [139]:
df2.head(1)

    timestamp  value sentiment_class  trade_date
0  1517463000     30            Fear  2018-02-01

In [140]:
df2["trade_date"] = pd.to_datetime(df2["trade_date"])

In [141]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   timestamp        2644 non-null   int64
 1   value            2644 non-null   int64
 2   sentiment_class  2644 non-null   object
 3   trade_date       2644 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 82.8+ KB

In [142]:
df2.drop(columns=["timestamp"], axis=1, inplace=True)

In [143]:
df2["trade_date"].nunique

<bound method IndexOpsMixin.nunique of 0      2018-02-01
1      2018-02-02
2      2018-02-03
3      2018-02-04
4      2018-02-05
          ...
2639   2025-04-28
2640   2025-04-29
2641   2025-04-30
2642   2025-05-01
2643   2025-05-02
Name: trade_date, Length: 2644, dtype: datetime64[ns]>

In [144]:
print("Trades from daily trades data", daily_df["trade_date"].min(), "to", daily_df["trade_date"].max())
print("Trades from sentiment data", df2["trade_date"].min(), "to", df2["trade_date"].max())

Trades from daily trades data 2023-05-01 00:00:00 to 2025-05-01 00:00:00
Trades from sentiment data 2018-02-01 00:00:00 to 2025-05-02 00:00:00

In [145]:
min_date= daily_df["trade_date"].min()
max_date= daily_df["trade_date"].max()

df2 = df2[(df2["trade_date"]>= min_date) & (df2["trade_date"]<=max_date)]

print("Trades from daily trades data", daily_df["trade_date"].min(), "to", daily_df["trade_date"].max())
print("Trades from sentiment data", df2["trade_date"].min(), "to", df2["trade_date"].max())

Trades from daily trades data 2023-05-01 00:00:00 to 2025-05-01 00:00:00
Trades from sentiment data 2023-05-01 00:00:00 to 2025-05-01 00:00:00

In [146]:
df2

      value sentiment_class trade_date
1912     63           Greed 2023-05-01
1913     55           Greed 2023-05-02
1914     64           Greed 2023-05-03
1915     64           Greed 2023-05-04
1916     61           Greed 2023-05-05
...     ...             ...        ...
2638     61           Greed 2025-04-27
2639     54         Neutral 2025-04-28
2640     60           Greed 2025-04-29
2641     56           Greed 2025-04-30
2642     53         Neutral 2025-05-01

[731 rows x 3 columns]

In [147]:
merged_df= daily_df.merge(df2, on="trade_date", how="left")

In [148]:
merged_df.shape

(2341, 10)

In [149]:
merged_df

,Account,trade_date,total_daily_pnl,num_trades,wins,avg_size_used,avg_fee,win_rate,value,sentiment_class
0,0x083384f897ee0f19899168e3b1bec365f52a9012,2024-11-11,0.000000,177,0,5089.718249,0.948000,0.000000,76.0,Extreme Greed
1,0x083384f897ee0f19899168e3b1bec365f52a9012,2024-11-17,0.000000,68,0,7976.664412,0.998288,0.000000,90.0,Extreme Greed
2,0x083384f897ee0f19899168e3b1bec365f52a9012,2024-11-18,0.000000,40,0,23734.500000,2.373450,0.000000,83.0,Extreme Greed
3,0x083384f897ee0f19899168e3b1bec365f52a9012,2024-11-22,-21227.000000,12,0,28186.666667,2.818666,0.000000,94.0,Extreme Greed
4,0x083384f897ee0f19899168e3b1bec365f52a9012,2024-11-26,1603.100000,27,12,17248.148148,3.874907,0.444444,79.0,Extreme Greed
...,...,...,...,...,...,...,...,...,...,...
2336,0xbee1707d6b44d4d52bfe19e41f8a828645437aab,2025-04-27,1709.194807,82,32,2153.859390,0.312681,0.390244,61.0,Greed
2337,0xbee1707d6b44d4d52bfe19e41f8a828645437aab,2025-04-28,4008.588908,430,169,1495.538419,0.371047,0.393023,54.0,Neutral
2338,0xbee1707d6b44d4d52bfe19e41f8a828645437aab,2025-04-29,8561.771838,902,398,1939.739989,0.386831,0.441242,60.0,Greed
2339,0xbee1707d6b44d4d52bfe19e41f8a828645437aab,2025-04-30,2520.773814,75,39,1748.805333,0.270870,0.520000,56.0,Greed
2340,0xbee1707d6b44d4d52bfe19e41f8a828645437aab,2025-05-01,1364.022527,131,43,2448.466489,0.457253,0.328244,53.0,Neutral

In [150]:
import os
folder_path = r"D:\Vanshika_reja\Need\CSV_files"

os.makedirs(folder_path, exist_ok=True)

file_path = os.path.join(folder_path, "merged_trader_sentiment.csv")

merged_df.to_csv(file_path, index=False)